### ISSUE TITLE
None Of The Templates Are Logging

### ISSUE THREAD

**Issue by KaptianCore** [kleo/evilportals#25]
Hey, I am having an issue with having the first login page I try to get it to log the info they log in with but it just won't work I am unsure if I am meant to do any further config. I will probably have issues with the other templates but the first one is giving me problems.

EDIT: none of the templates I have tried log: Google, Yahoo, Facebook, Starbucks & Twitter. Also is it meant to say you are not authorized every time?

Thanks, Kaptian Core

**Comment by novalokhd** [comment]
@KaptianCore - I thought they same thing..... however they are working.. they just don't say to the typical folder that EvilPortal is looking for them. They are in the root folder... 

root@Pineapple:/# cd root
root@Pineapple:~# ls
dead.letter      evilportal-logs  portals

Look in the evilportal-logs folder and there will be a text file there

**Comment by H4xl0r** [comment]
tell me where else they should be and i will add a copy or move the content

**Comment by kleo** [comment]
Logs can be found at /sd/portals/portal-login/.logs or at the web interface on EvilPortal module > Logs > View
