### ISSUE TITLE
Is it possible to use the pages from wifiphisher too?

### ISSUE THREAD

**Issue by hemstremp** [kleo/evilportals#30]
I've been trying for some hours but i'm kinda stuck as i don't know that much about html and php, but how can i make the pages from "https://github.com/wifiphisher/extra-phishing-pages" work on evil portals on the pineapple?
If i move them to the folder it finds them but i can't activate them

**Comment by kbeflo** [comment]
Pages from extra-phishing-pages are not compatible with the EvilPortal module. You can use the portals from this repo or make one.
