### ISSUE TITLE
Netflix evil portal

### ISSUE THREAD

**Issue by bruvv** [kleo/evilportals#31]
Crosslinking this for extra portals:
https://github.com/JonnyBanana/Netflix_EVIL_PORTAL

**Comment by JonnyBanana** [comment]
> Crosslinking this for extra portals: https://github.com/JonnyBanana/Netflix_EVIL_PORTAL

Thank you for requesting to add my repo, I was about to open an issue, but I see that it is not needed,
 however if you want to add it it's fine

**Comment by kleo** [comment]
I apologize, I don't have much time to work on this. I'll reopen this issue once I can get to it. Thank you guys.
